//
// Test Bench Module Project_lib.TOP_tb.TOP_tester
//
// Created:
//          by - benmaorr.UNKNOWN (L330W516)
//          at - 14:51:04 11/23/2021
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
//
`resetall
`timescale 1ns/10ps

module TOP_tb;

// Local declarations
parameter DATA_WIDTH = 32;
parameter AMBA_ADDR_WIDTH = 20;
parameter AMBA_WORD = 32;
parameter IDLE = 2'b00;
parameter ENCODING = 2'b01;
parameter DECODING = 2'b10;
parameter NOISING = 2'b11;

// Internal signal declarations
logic                         clk = 1'b0;
logic                         rst= 1'b0;
logic [AMBA_ADDR_WIDTH - 1:0] PADDR;
logic [AMBA_WORD - 1:0]       PWDATA;
logic                         PENABLE;
logic                         PSEL;
logic                         PWRITE;
logic [AMBA_WORD - 1:0]       PRDATA;
logic [DATA_WIDTH - 1:0]      data_out;
logic                         operation_done;


TOP #(32,20,32) U_0(
   .clk            (clk),
   .rst            (rst),
   .PADDR          (PADDR),
   .PWDATA         (PWDATA),
   .PENABLE        (PENABLE),
   .PSEL           (PSEL),
   .PWRITE         (PWRITE),
   .PRDATA         (PRDATA),
   .data_out       (data_out),
   .operation_done (operation_done)
);



//clock always block:
always
#1 clk <=~clk;

initial begin
#10.2ns;  //asyncrounsly de-assert asrtn
rst <= 1'b0;
#10;
@(posedge clk) rst <= 1'b1;

repeat(10)@(posedge clk);

// WRITE TO REGISTERS TEST

PWDATA <= {AMBA_WORD{1'b1}}; // 11111111
PADDR <= {{AMBA_ADDR_WIDTH-4{1'b0}},{4'b0100}}; // DATA
PSEL <= 1'b1;
PWRITE <= 1'b1;

#2;
PENABLE <= 1'b1;
#2;
PSEL <= 1'b0;
PENABLE <= 1'b0;

repeat(5)@(posedge clk);

PWDATA <= {{AMBA_WORD-1{1'b1}},{1'b0}};  //// 11111___ 10
PADDR <= {{AMBA_ADDR_WIDTH-4{1'b0}},{4'b1000}}; // DATA
PSEL <= 1'b1;

#2;
PENABLE <= 1'b1;
#2;
PSEL <= 1'b0;
PENABLE <= 1'b0;

repeat(5)@(posedge clk);

PWDATA <= {{AMBA_WORD-2{1'b1}},{2'b00}}; // 11111__1100
PADDR <= {{AMBA_ADDR_WIDTH-4{1'b0}},{4'b1100}}; // DATA
PSEL <= 1'b1;

#2;
PENABLE <= 1'b1;
#2;
PSEL <= 1'b0;
PENABLE <= 1'b0;

repeat(5)@(posedge clk);

PWDATA <= {{AMBA_WORD-3{1'b1}},{3'b000}}; // 11111__11000
PADDR <= {{AMBA_ADDR_WIDTH-4{1'b0}},{4'b0000}}; // DATA
PSEL <= 1'b1;

#2;
PENABLE <= 1'b1;
#2;
PSEL <= 1'b0;
PENABLE <= 1'b0;

// READ FROM REGISTERS TEST
PWRITE <= 1'b0;

//CTRL
repeat(10)@(posedge clk);

PADDR <= {{AMBA_ADDR_WIDTH-4{1'b0}},{4'b0000}}; // DATA
PSEL <= 1'b1;

#2;
PENABLE <= 1'b1;
#2;
PSEL <= 1'b0;
PENABLE <= 1'b0;

//DATA_IN
repeat(10)@(posedge clk);

PADDR <= {{AMBA_ADDR_WIDTH-4{1'b0}},{4'b0100}}; // DATA
PSEL <= 1'b1;

#2;
PENABLE <= 1'b1;
#2;
PSEL <= 1'b0;
PENABLE <= 1'b0;

//WIDTH
repeat(10)@(posedge clk);

PADDR <= {{AMBA_ADDR_WIDTH-4{1'b0}},{4'b1000}}; // DATA
PSEL <= 1'b1;

#2;
PENABLE <= 1'b1;
#2;
PSEL <= 1'b0;
PENABLE <= 1'b0;

//NOISE
repeat(10)@(posedge clk);

PADDR <= {{AMBA_ADDR_WIDTH-4{1'b0}},{4'b1100}}; // DATA
PSEL <= 1'b1;

#2;
PENABLE <= 1'b1;
#2;
PSEL <= 1'b0;
PENABLE <= 1'b0;




#100
$finish(0);
end


endmodule // TOP_tb


